channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - bzip2=1.0.8
  - c-ares=1.11.0
  - ca-certificates=2020.12.5
  - cairo=1.14.12
  - curl=7.71.1
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.55.0
  - graphite2=1.3.13
  - gsl=2.6
  - harfbuzz=1.9.0
  - icu=58.2
  - jpeg=9d
  - krb5=1.17.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libedit=3.1.20170329
  - libev=4.33
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.34
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.0.9
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - ncurses=5.9
  - openssl=1.1.1i
  - pango=1.40.14
  - pcre=8.39
  - pixman=0.34.0
  - pthread-stubs=0.4
  - r-assertthat=0.2.0
  - r-base=3.4.1
  - r-bh=1.62.0_1
  - r-bindr=0.1
  - r-bindrcpp=0.2
  - r-dplyr=0.7.0
  - r-getopt=1.20.2
  - r-glue=1.1.1
  - r-magrittr=1.5
  - r-optparse=1.6.0
  - r-peer=1.3
  - r-pkgconfig=2.0.1
  - r-plogr=0.1_1
  - r-r6=2.2.1
  - r-rcpp=0.12.11
  - r-rlang=0.1.1
  - r-tibble=1.3.3
  - readline=7.0
  - tk=8.6.10
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
